name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Install Dependencies
      run: |
        cd sam_lambda_cand30/hello_world
        pip install -r requirements.txt

    - name: Deploy SAM Application
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-1
      run: |
        cd sam_lambda_cand30
        sam deploy --no-confirm-changeset --stack-name cand30-sam-stack --capabilities CAPABILITY_IAM --region eu-west-1 --no-fail-on-empty-changeset || true
